### ISSUE TITLE
Введение '

### ISSUE THREAD

**Issue by mysmah** [mysmah/katuni#19]
Предлагаю такой список:

* В существительном единственного числа иминительного падежа -i заменять на '

* lu = l'

* Esteke = est'

**Comment by dpkit874** [comment]
1. такое сокращение может вызывать проблему того, что может изменяться фонация звука, что может привести к конфликтам и к неясности речи. Если даже эта "угроза" преувеличена, в любом случае правило "как пишется, так и читается" в этом случае нарушается.

2. вызывает конфликты тоже.

3. исключение, с которыми мы боремся.

**Comment by mysmah** [comment]
ок
